image: gradle:6.6.1-jdk11

clone:
  depth: full

pipelines:
  default:
    - parallel:
        - step:
            name: LintKotlin
            caches:
              - gradle
            script:
              - gradle lintKotlin
        - step:
            name: Build
            caches:
              - gradle
            script:
              - gradle build -x lintKotlin -x test
            artifacts:
              - build/**
        - step:
            name: Test
            caches:
              - gradle
            script:
              - gradle build jacocoTestReport sonarqube
        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.4.3

