app:
  description: ${app.name} is a Spring Boot application
  default-image-id: f702f3b5-9851-401f-8833-96f77374aad5
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  kafka:
    producer:
      bootstrap-servers: ${FAMILY_KAFKA_TLS_HOST:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${FAMILY_KAFKA_TLS_HOST:localhost:9092}
      group-id: shared_images
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  servlet:
    multipart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS

  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  error:
    include-stacktrace: never
logging:
  level:
    tul:
      com:
        examples:
          spring: TRACE
    org:
      springframework:
        cache: TRACE
tinify:
  url: ${TINIFY_URL:${random.value}}
  key: ${TINIFY_KEY:${random.value}}
aws:
  key-id: ${AWS_KEY_ID:${random.value}}
  secret-key: ${AWS_SECRET_KEY:${random.value}}
  region: ${AWS_REGION:${random.value}}
  bucket: ${AWS_BUCKET:${random.value}}