app:
  description: ${app.name} is a Spring Boot application
  tinify:
    url: https://api.tinify.com
    key: ${TINIFY_KEY:${random.value}}
  aws:
    key-id: ${AWS_KEY_ID:${random.value}}
    secret-key: ${AWS_SECRET_KEY:${random.value}}
    region: ${AWS_REGION:${random.value}}
    bucket: ${OWN_BUCKET_NAME:app}
spring:
  data:
    mongodb:
      uri: mongodb://${MS_NAME:app}:${FAMILY_DOCDB_PASSWORD:${random.value}}@${FAMILY_DOCDB_HOST:localhost}:27017/${MS_NAME:app}?readPreference=secondaryPreferred&retryWrites=false
  servlet:
    multipart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
server:
  error:
    include-stacktrace: never
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
    loggers:
      enabled: true