app:
  description: ${app.name} is a Spring Boot application
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS

  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  error:
    include-stacktrace: never
logging:
  level:
    tul:
      com:
        examples:
          spring: TRACE
    org:
      springframework:
        cache: TRACE