app:
  description: ${app.name} is a Spring Boot application
  tinify:
    url: ${TINIFY_URL:${random.value}}
    key: ${TINIFY_KEY:${random.value}}
  aws:
    key-id: ${AWS_KEY_ID:${random.value}}
    secret-key: ${AWS_SECRET_KEY:${random.value}}
    region: ${AWS_REGION:${random.value}}
    bucket: ${AWS_BUCKET:${random.value}}
spring:
  data:
    mongodb:
      host: ${FAMILY_DOCDB_HOST:localhost}
      port: 27017
      database: ${MS_NAME:app}
  kafka:
    bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
    consumer:
      group-id: default
  servlet:
    multipart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS

  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  error:
    include-stacktrace: never
logging:
  level:
    tul:
      com:
        examples:
          spring: TRACE
    org:
      springframework:
        cache: TRACE
